name: Sync Content

on:
  schedule:
    - cron: '0 2 * * *'  # sync every 10 AM PHT
  workflow_dispatch:

jobs:
  sync:
    name: Sync Content Submodule
    runs-on: ubuntu-latest
    permissions:
      contents: write
    defaults:
      run:
        shell: bash
    steps:
      - name: Checkout
        uses: actions/checkout@v5
        with:
          token: ${{ secrets.SYNCHRONIZE_CONTENT_TOKEN }}
          submodules: true
          fetch-depth: 0

      - name: Update submodule
        run: |
          git pull --recurse-submodules
          git submodule update --remote --recursive

      - name: Commit and push if changed
        env:
          SYNCHRONIZE_CONTENT_TOKEN: ${{ secrets.SYNCHRONIZE_CONTENT_TOKEN }}
        run: |
          git config --global user.name 'Git bot'
          git config --global user.email 'bot@noreply.github.com'
          git remote set-url origin https://x-access-token:${SYNCHRONIZE_CONTENT_TOKEN}@github.com/${{ github.repository }}
          git commit -am "🔄 content $(date -u '+%Y-%m-%dT%H:%M:%S.%3NZ')" && git push || echo "No changes to commit"
